name: x11-selection-tracker
synopsis: X11 selection interaction
maintainer: Philipp Balzarek
license: MIT

library:
  dependencies:
  - base
  - text
  - bytestring
  - mtl
  - containers
  - exceptions
  - unordered-containers
  - aeson
  - X11
  - inline-c
  - template-haskell
  c-sources:
    - src/Selection.c
  source-dirs: src
  extra-libraries:
    - Xfixes

# tests:
#   x11-selection-tracker-test-suite:
#     dependencies:
#     - base
#     - x11-selection-tracker
#     - tasty
#     - tasty-hspec
#     ghc-options:
#     - -rtsopts
#     - -threaded
#     - -with-rtsopts=-N
#     main: Main.hs
#     source-dirs: test-suite
# version: '0.0.0'
